nav:
  logo: /images/logo.png
  display_title: true
  fixed: false # fixed navigation bar

avatar:
  img: /images/avatar.png
  effect: true # 头像会一直转圈

menu:
  首页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fa fa-heartbeat:
    音乐: /music/ || fas fa-music
    照片: /Gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-heart

highlight_theme: light
highlight_copy: true
highlight_shrink: true #代码框不展开，需点击 '>' 打开

social:
  fab fa-github: https://github.com/jinghongbo || Github || "#hdhfbb"

default_top_img: /images/wallpaper/0194_山_海_雪.jpg